### PR TITLE
Activity stats

### PR DESCRIPTION
**Pull request by alexandra-aas**
- Derek needs to add actual numbers for stats

screencapture-localhost-3000-activities-1452187856351

### CODE REVIEW

**Comment by alexandra-aas** [comment]
@derekprior Not sure if you'll get around to this, but ready to go if you do.

**Comment by derekprior** [comment]
@jdaries is there a way we can know the current semester give a date?

**Comment by jdaries** [comment]
@derekprior we can make a guess, but may be slightly off due to shifts in day of week, calendar. I think in general, we could do the following:
Jan: JA
Feb through and including May: SP
June July August: SU
September through December: FA

**Comment by alexandra-aas** [comment]
@jdaries If there are other stats that seem more relevant we can use those instead. Just thought these might be helpful to Stephanie to have a more overarching idea of how on target they are for people adding data.

**Comment by jdaries** [comment]
@alexandra-aas i think those are good, but i realized that since SU isn't a choice for the results (we don't really have summer classes) then we should extend the SP dates through August

**Pull request closed without merging**
